env:
  browser: true
  es2021: true
settings:
  react:
    version: 'detect'
extends:
  - standard-with-typescript
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
rules:
  'react-hooks/rules-of-hooks': 'error'
  'react-hooks/exhaustive-deps': 'warn'
  'react/react-in-jsx-scope': 'off'
  '@typescript-eslint/space-before-function-paren': 'off'
  'import-helper/order-imports':
    - warn:
      newlinesBetween: always
      groups:
        [
          ['/ˆreact/', '/ˆnext/'],
          '/module/',
          '/^@shared/',
          '/absolute/',
          [parent, sibling, index]
        ]
      alphabetize:
        order: asc
        ignoreCase: true
